name: Core tests

on:
  push:
    branches: [ "master" ]
    paths:
      - workout-core/**
#  pull_request:
#    branches: [ "master" ]
#    paths:
#      - workout-core/**

jobs:
  #  name:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle Build
        run: ./gradlew build